### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by sniipo** [Hopeah/Project0#3]
### Brief

When a NON-logged user is open the <default_url>, it should be placed on a landing page.
The following sections should be on the page:
1. Logo
2. Welcome image/block 
3. Description of the service
4. Top navigation menu with the following items
     1. Login/SignUp
     2. Contact Us - see: [#4 :Contact Us page](https://github.com/Hopeah/Project0/issues/4)

### Technical details
1. When user clicks on Login/SignUp, an overlay appear where user can provide their credentials. 
2. ContactUs link opens a page (in the same browser window/tab).
5. The page should follow responsive design standards and can be scaled from Mobile to Desktop resolution

**Comment by sniipo** [comment]
@Hopeah I think this should be the next.
Actually, we need a design, so please link any related UI/Ideas so we can sync our expectations regarding required elements

**Comment by Hopeah** [comment]
A few interesting landing page designs: [one](https://html5up.net/landed), [two](https://templatemo.com/tm-543-breezed), [three](https://templatemo.com/tm-538-digital-trend)

**Comment by sniipo** [comment]
@Hopeah nice. Which one do you prefer?
